sudo: required
dist: trusty
language: cpp
compiler:
    - g++
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -yqq libpoppler-cpp-dev libsqlite3-dev libboost-filesystem-dev libboost-regex-dev
script: ./autogen.sh && ./configure && make -j2 && make check -j2
