.TH "bug" 3 "Sat Apr 11 2015" "pdfsearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBClass \fBPdfsearch::Pdf\fP \fP" 1c
poppler::page leaks\&. Am I doing something wrong or is there a bug in poppler? Currently, I'm using an old version of poppler, maybe updating fixes this\&. Update: poppler::document leaks with new version of poppler? poppler::page doesn't seem to leak\&. 
.PP

