# Case-insensitive and whitespace is ignored.
#database=~/.pdfsearch/pdfsearch.conf
# Separate with ','. Use '\,' if directory name has comma in it.
#directories=.
# 0 = unlimited matches
#matches=0
# -1 = recurse infinitely
#recursion=-1
#verbose=yes|no
